version: '3.2'

services:
  cards-ai-app:
    build:
      context: .
    container_name: cards-ai-app
    restart: always
    ports:
      - "8000:8000"
    command: [ "uvicorn main:app --host 0.0.0.0 --port 8000" ]